default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: herasufy_server_development

test:
  <<: *default
  database: herasufy_server_test
